name: Build Docker Image and Push to ECR

on: 
  push:
    branches: [ master ]
    
jobs:
  login-to-ecr:
    name: Login to Amazon ECR
    runs-on: ubuntu-latest
    outputs: 
      registry: ${{ steps.login-ecr.outputs.registry }}
    
  build:    
    name: Build, test and push image
    runs-on: ubuntu-latest
    needs: login-to-ecr
    strategy:
      matrix:
        ecr_repo: [cats, dogs]
    
    env:
      ECR_REGISTRY: ${{needs.login-to-ecr.outputs.registry}}
      ECR_REPO_PREFIX: ${{ secrets.ECR_REPO_PREFIX }}
      IMAGE_TAG: ${{ secrets.IMAGE_TAG }}
      REPO: ${{ matrix.ecr_repo }}
      
    steps:
    - name: Check out code
      uses: actions/checkout@v2
        
    - name: Build docker image
      run: |
        cd cats-and-dogs/$REPO/
        ls -ltra
        docker build -t $ECR_REGISTRY/$ECR_REPO_PREFIX-$REPO:$IMAGE_TAG .
    
    - name: Test docker image
      run: |
        docker run -d -p 80:80 --name $REPO-app $ECR_REGISTRY/$ECR_REPO_PREFIX-$REPO:$IMAGE_TAG
        docker ps
        echo "Pause for 10 seconds to let container start"
        sleep 10
        curl localhost -vvv

    - name: Push docker image to Amazon ECR
      run: |
        docker push $ECR_REGISTRY/$ECR_REPO_PREFIX-$REPO:$IMAGE_TAG
